version: "3.7"

services:
    web:
        build: ./web
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        volumes:
            - ./web/:/usr/src/app/
        ports:
            - 5000:5000
        env_file:
            - ./.env
        depends_on:
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flask_jwt_auth
            MYSQL_USER: user
            MYSQL_PASSWORD: user

        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
            - ./mysql_data:/var/lib/mysql

        ports:
            - 33306:3306
